In [23]:
import torch
from torch.autograd import Variable
import torch.nn as nn

In [24]:
x = Variable(torch.randn(10, 3))
print(x)
y = Variable(torch.FloatTensor(10, 3).random_(2))
print(y)

tensor([[-0.6684,  0.9501,  0.7455],
        [-1.5511, -0.5593, -0.4616],
        [-0.2792, -0.6318,  0.8696],
        [ 0.5621, -0.3480,  0.4634],
        [-1.0622,  0.0460,  1.4162],
        [-0.5642,  1.7867, -0.3784],
        [-0.5454, -0.4402,  0.4469],
        [-0.8599, -0.9066, -1.0315],
        [ 1.5087, -0.2591, -1.4231],
        [ 1.0720, -0.7051, -0.9798]])
tensor([[1., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 1.],
        [1., 0., 0.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 1., 1.],
        [1., 1., 1.]])


In [30]:
# double the loss for class 1

class_weight = torch.FloatTensor([0.25, 0.5, 0.25])
# class_weight = torch.FloatTensor([1.0, 2.0, 1.0])

# double the loss for last sample
element_weight = torch.FloatTensor([1.0]*9 + [2.0]).view(-1, 1)
element_weight = element_weight.repeat(1, 3)

In [31]:
bce_criterion = nn.BCEWithLogitsLoss(weight=None, reduce=False)
multi_criterion = nn.MultiLabelSoftMarginLoss(weight=None, reduce=False)

In [32]:
bce_criterion_class = nn.BCEWithLogitsLoss(weight=class_weight, reduce=False)
multi_criterion_class = nn.MultiLabelSoftMarginLoss(weight=class_weight, reduce=False)


bce_criterion_element = nn.BCEWithLogitsLoss(weight=element_weight, reduce=False)
multi_criterion_element = nn.MultiLabelSoftMarginLoss(weight=element_weight, reduce=False)

In [33]:
bce_loss = bce_criterion(x, y)
multi_loss = multi_criterion(x, y)

bce_loss_class = bce_criterion_class(x, y)
multi_loss_class = multi_criterion_class(x, y)

bce_loss_element = bce_criterion_element(x, y)
multi_loss_element = multi_criterion_element(x, y)

In [34]:
# print(torch.mean(bce_loss,dim=1))

print(multi_loss)

bce_loss = torch.mean(bce_loss,dim=1)

bce_loss_class = torch.mean(bce_loss_class,dim=1)

bce_loss_element = torch.mean(bce_loss_element,dim=1)

print(bce_loss, multi_loss)

print(bce_loss_class - multi_loss_class)

print(bce_loss_element - multi_loss_element)

tensor([0.9158, 0.8947, 0.9470, 0.9490, 0.7642, 1.1593, 0.8114, 0.3324, 1.3928,
        0.8999])
tensor([0.9158, 0.8947, 0.9470, 0.9490, 0.7642, 1.1593, 0.8114, 0.3324, 1.3928,
        0.8999]) tensor([0.9158, 0.8947, 0.9470, 0.9490, 0.7642, 1.1593, 0.8114, 0.3324, 1.3928,
        0.8999])
tensor([0.0000e+00, 2.9802e-08, 0.0000e+00, 0.0000e+00, 2.9802e-08, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([0.0000e+00, 0.0000e+00, 5.9605e-08, 1.1921e-07, 1.1921e-07, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])


In [35]:
li = [0.0326, 0.0333, 0.0452, 0.0248, 0.0334, 0.0255, 0.0976, 0.0461, 0.0609,
        0.0193, 0.0274, 0.0576, 0.0393, 0.0335, 0.2748, 0.0335, 0.0131, 0.0313,
        0.0357, 0.0350]
sum(li)

0.9998999999999999